//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseholdAccountBook.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HouseholdAccountBook.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        public static byte[] AppIcon {
            get {
                object obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   支出 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BalanceKind_Expenses {
            get {
                return ResourceManager.GetString("BalanceKind_Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   収入 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BalanceKind_Income {
            get {
                return ResourceManager.GetString("BalanceKind_Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   銀行口座 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BookKind_BankAccount {
            get {
                return ResourceManager.GetString("BookKind_BankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   証券口座 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BookKind_BrokerageAccount {
            get {
                return ResourceManager.GetString("BookKind_BrokerageAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クレジットカード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BookKind_CreditCard {
            get {
                return ResourceManager.GetString("BookKind_CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未分類 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BookKind_Uncategorized {
            get {
                return ResourceManager.GetString("BookKind_Uncategorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   財布 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string BookKind_Wallet {
            get {
                return ResourceManager.GetString("BookKind_Wallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_Add {
            get {
                return ResourceManager.GetString("Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分類追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_AddCategory {
            get {
                return ResourceManager.GetString("Button_AddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   項目追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_AddItem {
            get {
                return ResourceManager.GetString("Button_AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   まとめて追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_AddList {
            get {
                return ResourceManager.GetString("Button_AddList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全期間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_AllTerm {
            get {
                return ResourceManager.GetString("Button_AllTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   言語を適用する(再起動) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_ApplyLanguage {
            get {
                return ResourceManager.GetString("Button_ApplyLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ◀ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_Backward {
            get {
                return ResourceManager.GetString("Button_Backward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一括チェック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_BulkCheck {
            get {
                return ResourceManager.GetString("Button_BulkCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   閉じる に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   続けて入力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_Continue {
            get {
                return ResourceManager.GetString("Button_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   複製 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_Copy {
            get {
                return ResourceManager.GetString("Button_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   期間指定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_DateRange {
            get {
                return ResourceManager.GetString("Button_DateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ↓ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_DropSortOrder {
            get {
                return ResourceManager.GetString("Button_DropSortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ▶ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_Forward {
            get {
                return ResourceManager.GetString("Button_Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ✕ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_HideFind {
            get {
                return ResourceManager.GetString("Button_HideFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ▲ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_HideReplace {
            get {
                return ResourceManager.GetString("Button_HideReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   位置・サイズを初期化する(再起動) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_InitializeWindowPositionAndSize {
            get {
                return ResourceManager.GetString("Button_InitializeWindowPositionAndSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_Move {
            get {
                return ResourceManager.GetString("Button_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_OK {
            get {
                return ResourceManager.GetString("Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_Open {
            get {
                return ResourceManager.GetString("Button_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ↑ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_RaiseSortOrder {
            get {
                return ResourceManager.GetString("Button_RaiseSortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_Registration {
            get {
                return ResourceManager.GetString("Button_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データベース通信設定を再登録する(再起動) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_ReregisterDatabaseSetting {
            get {
                return ResourceManager.GetString("Button_ReregisterDatabaseSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ▼ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_ShowReplace {
            get {
                return ResourceManager.GetString("Button_ShowReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   今月 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_ThisMonth {
            get {
                return ResourceManager.GetString("Button_ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   今年 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_ThisYear {
            get {
                return ResourceManager.GetString("Button_ThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   今日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Button_Today {
            get {
                return ResourceManager.GetString("Button_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日付の自動インクリメント に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CheckBox_DateAutoIncrement {
            get {
                return ResourceManager.GetString("CheckBox_DateAutoIncrement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メインウィンドウ以外の位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CheckBox_SaveTarget_PositionWithoutMainWindow {
            get {
                return ResourceManager.GetString("CheckBox_SaveTarget_PositionWithoutMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CheckBox_Setting {
            get {
                return ResourceManager.GetString("CheckBox_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メインウィンドウクローズ時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CheckBox_Timing_ClosingMainWindow {
            get {
                return ResourceManager.GetString("CheckBox_Timing_ClosingMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   メインウィンドウ最小化時 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CheckBox_Timing_MinimizingMainWindow {
            get {
                return ResourceManager.GetString("CheckBox_Timing_MinimizingMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   金額 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColumnHeader_AmountOfMoney {
            get {
                return ResourceManager.GetString("ColumnHeader_AmountOfMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   平均 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColumnHeader_Average {
            get {
                return ResourceManager.GetString("ColumnHeader_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   残高 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColumnHeader_Balance {
            get {
                return ResourceManager.GetString("ColumnHeader_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   帳簿名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColumnHeader_BookName {
            get {
                return ResourceManager.GetString("ColumnHeader_BookName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分類名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColumnHeader_CategoryName {
            get {
                return ResourceManager.GetString("ColumnHeader_CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSV項目名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColumnHeader_CSVItemName {
            get {
                return ResourceManager.GetString("ColumnHeader_CSVItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日付 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColumnHeader_Date {
            get {
                return ResourceManager.GetString("ColumnHeader_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   曜日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColumnHeader_Day {
            get {
                return ResourceManager.GetString("ColumnHeader_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   支出 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColumnHeader_Expenses {
            get {
                return ResourceManager.GetString("ColumnHeader_Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   収入 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColumnHeader_Income {
            get {
                return ResourceManager.GetString("ColumnHeader_Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   項目名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColumnHeader_ItemName {
            get {
                return ResourceManager.GetString("ColumnHeader_ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最終使用日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColumnHeader_LastUsageDate {
            get {
                return ResourceManager.GetString("ColumnHeader_LastUsageDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一致 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColumnHeader_Match {
            get {
                return ResourceManager.GetString("ColumnHeader_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   備考 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColumnHeader_Remark {
            get {
                return ResourceManager.GetString("ColumnHeader_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   店名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColumnHeader_ShopName {
            get {
                return ResourceManager.GetString("ColumnHeader_ShopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   合計 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColumnHeader_Total {
            get {
                return ResourceManager.GetString("ColumnHeader_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使用回数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ColumnHeader_UsageCount {
            get {
                return ResourceManager.GetString("ColumnHeader_UsageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動元 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommissionKind_MoveFrom {
            get {
                return ResourceManager.GetString("CommissionKind_MoveFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommissionKind_MoveTo {
            get {
                return ResourceManager.GetString("CommissionKind_MoveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   英語(en-001) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CultureName_en_001 {
            get {
                return ResourceManager.GetString("CultureName_en_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日本語(ja-JP) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CultureName_ja_JP {
            get {
                return ResourceManager.GetString("CultureName_ja_JP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSVファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileSelectFilter_CsvFile {
            get {
                return ResourceManager.GetString("FileSelectFilter_CsvFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カスタム形式ファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileSelectFilter_CustomFormatFile {
            get {
                return ResourceManager.GetString("FileSelectFilter_CustomFormatFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MDBファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileSelectFilter_MdbFile {
            get {
                return ResourceManager.GetString("FileSelectFilter_MdbFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SQLファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileSelectFilter_SqlFile {
            get {
                return ResourceManager.GetString("FileSelectFilter_SqlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   残高 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GraphKind1_BalanceGraph {
            get {
                return ResourceManager.GetString("GraphKind1_BalanceGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   収支 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GraphKind1_IncomeAndExpensesGraph {
            get {
                return ResourceManager.GetString("GraphKind1_IncomeAndExpensesGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分類 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GraphKind2_CategoryGraph {
            get {
                return ResourceManager.GetString("GraphKind2_CategoryGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   項目 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GraphKind2_ItemGraph {
            get {
                return ResourceManager.GetString("GraphKind2_ItemGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日別グラフ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GraphTitle_DailyGraph {
            get {
                return ResourceManager.GetString("GraphTitle_DailyGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   月別グラフ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GraphTitle_MonthlyGraph {
            get {
                return ResourceManager.GetString("GraphTitle_MonthlyGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   個別グラフ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GraphTitle_SeparetelyGraph {
            get {
                return ResourceManager.GetString("GraphTitle_SeparetelyGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   年別グラフ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GraphTitle_YearlyGraph {
            get {
                return ResourceManager.GetString("GraphTitle_YearlyGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Microsoft Access(記帳風月) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupHeader_Access {
            get {
                return ResourceManager.GetString("GroupHeader_Access", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バックアップ情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupHeader_BackUpInformation {
            get {
                return ResourceManager.GetString("GroupHeader_BackUpInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   帳簿情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupHeader_BookInformation {
            get {
                return ResourceManager.GetString("GroupHeader_BookInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   帳簿一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupHeader_BookList {
            get {
                return ResourceManager.GetString("GroupHeader_BookList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カレンダー情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupHeader_CalendarInformation {
            get {
                return ResourceManager.GetString("GroupHeader_CalendarInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   列番号 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupHeader_ColumnIndex {
            get {
                return ResourceManager.GetString("GroupHeader_ColumnIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSV情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupHeader_CSVInformation {
            get {
                return ResourceManager.GetString("GroupHeader_CSVInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データベース情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupHeader_DataBaseInformation {
            get {
                return ResourceManager.GetString("GroupHeader_DataBaseInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デバッグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupHeader_Debug {
            get {
                return ResourceManager.GetString("GroupHeader_Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   祝日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupHeader_Holiday {
            get {
                return ResourceManager.GetString("GroupHeader_Holiday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   項目情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupHeader_ItemInformation {
            get {
                return ResourceManager.GetString("GroupHeader_ItemInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   項目一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupHeader_ItemList {
            get {
                return ResourceManager.GetString("GroupHeader_ItemList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   言語情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupHeader_LanguageInformation {
            get {
                return ResourceManager.GetString("GroupHeader_LanguageInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   関連付け に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupHeader_Linkage {
            get {
                return ResourceManager.GetString("GroupHeader_Linkage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定月 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupHeader_MonthSelection {
            get {
                return ResourceManager.GetString("GroupHeader_MonthSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   支払情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupHeader_PaymentInformation {
            get {
                return ResourceManager.GetString("GroupHeader_PaymentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PostgreSQL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupHeader_PostgreSQL {
            get {
                return ResourceManager.GetString("GroupHeader_PostgreSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   備考 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupHeader_Remark {
            get {
                return ResourceManager.GetString("GroupHeader_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   店舗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupHeader_Shop {
            get {
                return ResourceManager.GetString("GroupHeader_Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   期間情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupHeader_TermInformation {
            get {
                return ResourceManager.GetString("GroupHeader_TermInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定期間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupHeader_TermSelection {
            get {
                return ResourceManager.GetString("GroupHeader_TermSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ウィンドウ情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GroupHeader_WindowInformation {
            get {
                return ResourceManager.GetString("GroupHeader_WindowInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   休日後 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HolidaySettingKind_AfterHoliday {
            get {
                return ResourceManager.GetString("HolidaySettingKind_AfterHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   休日前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HolidaySettingKind_BeforeHoliday {
            get {
                return ResourceManager.GetString("HolidaySettingKind_BeforeHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   なし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HolidaySettingKind_Nothing {
            get {
                return ResourceManager.GetString("HolidaySettingKind_Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListName_AllBooks {
            get {
                return ResourceManager.GetString("ListName_AllBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   残高 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListName_Balance {
            get {
                return ResourceManager.GetString("ListName_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   繰越残高 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListName_CarryForward {
            get {
                return ResourceManager.GetString("ListName_CarryForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   なし に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListName_None {
            get {
                return ResourceManager.GetString("ListName_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (指定なし) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListName_NoSpecification {
            get {
                return ResourceManager.GetString("ListName_NoSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   差引損益 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ListName_profitAndLoss {
            get {
                return ResourceManager.GetString("ListName_profitAndLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集(_E) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Edit {
            get {
                return ResourceManager.GetString("Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   追加(_A)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Edit_Add {
            get {
                return ResourceManager.GetString("Menu_Edit_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リスト追加(_W)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Edit_AddList {
            get {
                return ResourceManager.GetString("Menu_Edit_AddList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一括チェック(_B) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Edit_BulkCheck {
            get {
                return ResourceManager.GetString("Menu_Edit_BulkCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   複製(_C)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Edit_Copy {
            get {
                return ResourceManager.GetString("Menu_Edit_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除(_D) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Edit_Delete {
            get {
                return ResourceManager.GetString("Menu_Edit_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集(_E)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Edit_Edit {
            get {
                return ResourceManager.GetString("Menu_Edit_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索(_F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Edit_Find {
            get {
                return ResourceManager.GetString("Menu_Edit_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動(_T)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Edit_Move {
            get {
                return ResourceManager.GetString("Menu_Edit_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   置換(_H) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Edit_Replace {
            get {
                return ResourceManager.GetString("Menu_Edit_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル(_F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File {
            get {
                return ResourceManager.GetString("Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バックアップ(_B) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File_Backup {
            get {
                return ResourceManager.GetString("Menu_File_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   閉じる(_C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File_Close {
            get {
                return ResourceManager.GetString("Menu_File_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了(_F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File_Exit {
            get {
                return ResourceManager.GetString("Menu_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エクスポート(_E) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File_Export {
            get {
                return ResourceManager.GetString("Menu_File_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カスタム形式ファイル(_C)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File_Export_CustomFormatFile {
            get {
                return ResourceManager.GetString("Menu_File_Export_CustomFormatFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Excel(_E)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File_Export_Excel {
            get {
                return ResourceManager.GetString("Menu_File_Export_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SQLファイル(_S)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File_Export_SQLFile {
            get {
                return ResourceManager.GetString("Menu_File_Export_SQLFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インポート(_I) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File_Import {
            get {
                return ResourceManager.GetString("Menu_File_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カスタム形式ファイル(_C)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File_Import_CustomFormatFile {
            get {
                return ResourceManager.GetString("Menu_File_Import_CustomFormatFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   記帳風月(_K)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File_Import_KichoFugetsu {
            get {
                return ResourceManager.GetString("Menu_File_Import_KichoFugetsu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動(_M) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File_Move {
            get {
                return ResourceManager.GetString("Menu_File_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開く(_O)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_File_Open {
            get {
                return ResourceManager.GetString("Menu_File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ヘルプ(_H) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョン情報(_V)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Help_VersionInfo {
            get {
                return ResourceManager.GetString("Menu_Help_VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ツール(_T) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Tool {
            get {
                return ResourceManager.GetString("Menu_Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   帳簿(_B) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Tool_Book {
            get {
                return ResourceManager.GetString("Menu_Tool_Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フィルタ(_F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Tool_Book_Filter {
            get {
                return ResourceManager.GetString("Menu_Tool_Book_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSV比較(_C)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Tool_CsvComparison {
            get {
                return ResourceManager.GetString("Menu_Tool_CsvComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定(_S)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Tool_Settings {
            get {
                return ResourceManager.GetString("Menu_Tool_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示(_V) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_View {
            get {
                return ResourceManager.GetString("Menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   帳簿(_B) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_View_Book {
            get {
                return ResourceManager.GetString("Menu_View_Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   切替(_C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_View_Book_Change {
            get {
                return ResourceManager.GetString("Menu_View_Book_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   期間指定(_S)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_View_Book_DailyTermSelection {
            get {
                return ResourceManager.GetString("Menu_View_Book_DailyTermSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   先月(_L) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_View_Book_LastMonth {
            get {
                return ResourceManager.GetString("Menu_View_Book_LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   来月(_N) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_View_Book_NextMonth {
            get {
                return ResourceManager.GetString("Menu_View_Book_NextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   今月(_T) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_View_Book_ThisMonth {
            get {
                return ResourceManager.GetString("Menu_View_Book_ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日別グラフ(_G) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_View_DailyGraph {
            get {
                return ResourceManager.GetString("Menu_View_DailyGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   切替(_C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_View_DailyGraph_Change {
            get {
                return ResourceManager.GetString("Menu_View_DailyGraph_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   期間指定(_S)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_View_DailyGraph_DailyTermSelection {
            get {
                return ResourceManager.GetString("Menu_View_DailyGraph_DailyTermSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   先月(_L) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_View_DailyGraph_LastMonth {
            get {
                return ResourceManager.GetString("Menu_View_DailyGraph_LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   来月(_N) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_View_DailyGraph_NextMonth {
            get {
                return ResourceManager.GetString("Menu_View_DailyGraph_NextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   今月(_T) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_View_DailyGraph_ThisMonth {
            get {
                return ResourceManager.GetString("Menu_View_DailyGraph_ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   月別(_M) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_View_Monthly {
            get {
                return ResourceManager.GetString("Menu_View_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グラフ(_G) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_View_MonthlyGraph {
            get {
                return ResourceManager.GetString("Menu_View_MonthlyGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   切替(_C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_View_MonthlyGraph_Change {
            get {
                return ResourceManager.GetString("Menu_View_MonthlyGraph_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   去年(_L) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_View_MonthlyGraph_LastYear {
            get {
                return ResourceManager.GetString("Menu_View_MonthlyGraph_LastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   来年(_N) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_View_MonthlyGraph_NextYear {
            get {
                return ResourceManager.GetString("Menu_View_MonthlyGraph_NextYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   今年(_T) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_View_MonthlyGraph_ThisYear {
            get {
                return ResourceManager.GetString("Menu_View_MonthlyGraph_ThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一覧(_L) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_View_MonthlyList {
            get {
                return ResourceManager.GetString("Menu_View_MonthlyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   切替(_C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_View_MonthlyList_Change {
            get {
                return ResourceManager.GetString("Menu_View_MonthlyList_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   去年(_L) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_View_MonthlyList_LastYear {
            get {
                return ResourceManager.GetString("Menu_View_MonthlyList_LastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   来年(_N) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_View_MonthlyList_NextYear {
            get {
                return ResourceManager.GetString("Menu_View_MonthlyList_NextYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   今年(_T) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_View_MonthlyList_ThisYear {
            get {
                return ResourceManager.GetString("Menu_View_MonthlyList_ThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新(_U) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_View_Update {
            get {
                return ResourceManager.GetString("Menu_View_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   年別(_Y) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_View_Yearly {
            get {
                return ResourceManager.GetString("Menu_View_Yearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   グラフ(_G) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_View_YearlyGraph {
            get {
                return ResourceManager.GetString("Menu_View_YearlyGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   切替(_C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_View_YearlyGraph_Change {
            get {
                return ResourceManager.GetString("Menu_View_YearlyGraph_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一覧(_L) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_View_YearlyList {
            get {
                return ResourceManager.GetString("Menu_View_YearlyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   切替(_C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_View_YearlyList_Change {
            get {
                return ResourceManager.GetString("Menu_View_YearlyList_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   帳簿内に帳簿項目が存在するので削除できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_CantDeleteBecauseActionItemExistsInBook {
            get {
                return ResourceManager.GetString("Message_CantDeleteBecauseActionItemExistsInBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分類内に帳簿項目が存在するので削除できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_CantDeleteBecauseActionItemExistsInCategory {
            get {
                return ResourceManager.GetString("Message_CantDeleteBecauseActionItemExistsInCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   項目内に帳簿項目が存在するので削除できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_CantDeleteBecauseActionItemExistsInItem {
            get {
                return ResourceManager.GetString("Message_CantDeleteBecauseActionItemExistsInItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   帳簿内の該当する項目に帳簿項目が存在するので削除できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_CantDeleteBecauseActionItemExistsInItemWithinBook {
            get {
                return ResourceManager.GetString("Message_CantDeleteBecauseActionItemExistsInItemWithinBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択した項目を削除します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_DeleteNotification {
            get {
                return ResourceManager.GetString("Message_DeleteNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   既存のデータを削除します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_DeleteOldDataNotification {
            get {
                return ResourceManager.GetString("Message_DeleteOldDataNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同時に複数起動することはできません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_DoNotDuplicateProcess {
            get {
                return ResourceManager.GetString("Message_DoNotDuplicateProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バックアップが完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_FinishToBackup {
            get {
                return ResourceManager.GetString("Message_FinishToBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エクスポートが完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_FinishToExport {
            get {
                return ResourceManager.GetString("Message_FinishToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インポートが完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_FinishToImport {
            get {
                return ResourceManager.GetString("Message_FinishToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存が完了しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_FinishToSave {
            get {
                return ResourceManager.GetString("Message_FinishToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バックアップに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_FoultToBackup {
            get {
                return ResourceManager.GetString("Message_FoultToBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続に失敗しました。接続設定を見直してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_FoultToConnectDb {
            get {
                return ResourceManager.GetString("Message_FoultToConnectDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エクスポートに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_FoultToExport {
            get {
                return ResourceManager.GetString("Message_FoultToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インポートに失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_FoultToImport {
            get {
                return ResourceManager.GetString("Message_FoultToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSVファイルの移動に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_FoultToMoveCsv {
            get {
                return ResourceManager.GetString("Message_FoultToMoveCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DB接続設定を入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_PleaseInputDbSetting {
            get {
                return ResourceManager.GetString("Message_PleaseInputDbSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} を {1} に置き換えます。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_ReplaceShopNameRemarkNotification {
            get {
                return ResourceManager.GetString("Message_ReplaceShopNameRemarkNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再起動します。よろしいですか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_RestartNotification {
            get {
                return ResourceManager.GetString("Message_RestartNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ハンドルされていない例外が発生しました。クリックで例外の情報を確認できます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Message_UnhandledExceptionOccurred {
            get {
                return ResourceManager.GetString("Message_UnhandledExceptionOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力ウィンドウを表示する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RadioButton_Password_ShowInputWindow {
            get {
                return ResourceManager.GetString("RadioButton_Password_ShowInputWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   pgpass.conf を指定する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RadioButton_Password_SpecifyPgpassConf {
            get {
                return ResourceManager.GetString("RadioButton_Password_SpecifyPgpassConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   帳簿 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabHeader_AccountBook {
            get {
                return ResourceManager.GetString("TabHeader_AccountBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   帳簿設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabHeader_BookSettings {
            get {
                return ResourceManager.GetString("TabHeader_BookSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日別
        ///グラフ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabHeader_DailyGraph {
            get {
                return ResourceManager.GetString("TabHeader_DailyGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   項目設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabHeader_ItemSettings {
            get {
                return ResourceManager.GetString("TabHeader_ItemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   月別
        ///グラフ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabHeader_MonthlyGraph {
            get {
                return ResourceManager.GetString("TabHeader_MonthlyGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   月別
        ///一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabHeader_MonthlySummary {
            get {
                return ResourceManager.GetString("TabHeader_MonthlySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   その他 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabHeader_OtherSettings {
            get {
                return ResourceManager.GetString("TabHeader_OtherSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   年別
        ///グラフ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabHeader_YearlyGraph {
            get {
                return ResourceManager.GetString("TabHeader_YearlyGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   年別
        ///一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TabHeader_YearlySummary {
            get {
                return ResourceManager.GetString("TabHeader_YearlySummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DBファイル名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_Access_DBFilePath {
            get {
                return ResourceManager.GetString("TextBlock_Access_DBFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロバイダ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_Access_Provider {
            get {
                return ResourceManager.GetString("TextBlock_Access_Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   金額 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_AmountOfMoney {
            get {
                return ResourceManager.GetString("TextBlock_AmountOfMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   平均 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_Average {
            get {
                return ResourceManager.GetString("TextBlock_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   帳簿 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_Book {
            get {
                return ResourceManager.GetString("TextBlock_Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   帳簿種別 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_BookKind {
            get {
                return ResourceManager.GetString("TextBlock_BookKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   帳簿名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_BookName {
            get {
                return ResourceManager.GetString("TextBlock_BookName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   帳簿 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_Books {
            get {
                return ResourceManager.GetString("TextBlock_Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   負担 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_Burden {
            get {
                return ResourceManager.GetString("TextBlock_Burden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分類 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_Category {
            get {
                return ResourceManager.GetString("TextBlock_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分類名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_CategoryName {
            get {
                return ResourceManager.GetString("TextBlock_CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チェック済 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_Checked {
            get {
                return ResourceManager.GetString("TextBlock_Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   列目 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_ColumnUnit {
            get {
                return ResourceManager.GetString("TextBlock_ColumnUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   手数料 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_Comission {
            get {
                return ResourceManager.GetString("TextBlock_Comission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   個数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_Count {
            get {
                return ResourceManager.GetString("TextBlock_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSVファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_CsvFiles {
            get {
                return ResourceManager.GetString("TextBlock_CsvFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSVフォルダ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_CsvFolder {
            get {
                return ResourceManager.GetString("TextBlock_CsvFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データの個数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_DataCount {
            get {
                return ResourceManager.GetString("TextBlock_DataCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日付 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_Date {
            get {
                return ResourceManager.GetString("TextBlock_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DB種別 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_DBKind {
            get {
                return ResourceManager.GetString("TextBlock_DBKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_EndDate {
            get {
                return ResourceManager.GetString("TextBlock_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   支出 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_Expenses {
            get {
                return ResourceManager.GetString("TextBlock_Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   絞り込み に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_Filter {
            get {
                return ResourceManager.GetString("TextBlock_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   フォルダパス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_FolderPath {
            get {
                return ResourceManager.GetString("TextBlock_FolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   収支 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_IncomeOrExpenses {
            get {
                return ResourceManager.GetString("TextBlock_IncomeOrExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   初期残高 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_InitialBalance {
            get {
                return ResourceManager.GetString("TextBlock_InitialBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インターバル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_Interval {
            get {
                return ResourceManager.GetString("TextBlock_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   項目 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_Item {
            get {
                return ResourceManager.GetString("TextBlock_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   項目名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_ItemName {
            get {
                return ResourceManager.GetString("TextBlock_ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   言語 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_Language {
            get {
                return ResourceManager.GetString("TextBlock_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最後に操作した帳簿項目 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_LastOperatedBookItem {
            get {
                return ResourceManager.GetString("TextBlock_LastOperatedBookItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_MinutesUnit {
            get {
                return ResourceManager.GetString("TextBlock_MinutesUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動元 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_MoveFrom {
            get {
                return ResourceManager.GetString("TextBlock_MoveFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動先 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_MoveTo {
            get {
                return ResourceManager.GetString("TextBlock_MoveTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DB名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_Npgsql_DbName {
            get {
                return ResourceManager.GetString("TextBlock_Npgsql_DbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ホスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_Npgsql_Host {
            get {
                return ResourceManager.GetString("TextBlock_Npgsql_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_Npgsql_Password {
            get {
                return ResourceManager.GetString("TextBlock_Npgsql_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ポート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_Npgsql_Port {
            get {
                return ResourceManager.GetString("TextBlock_Npgsql_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ロール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_Npgsql_Roll {
            get {
                return ResourceManager.GetString("TextBlock_Npgsql_Roll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユーザ名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_Npgsql_UserName {
            get {
                return ResourceManager.GetString("TextBlock_Npgsql_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワード に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_Password {
            get {
                return ResourceManager.GetString("TextBlock_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   支払元帳簿 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_PaymentBook {
            get {
                return ResourceManager.GetString("TextBlock_PaymentBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   支払日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_PaymentDate {
            get {
                return ResourceManager.GetString("TextBlock_PaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   備考 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_Remark {
            get {
                return ResourceManager.GetString("TextBlock_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   繰り返し に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_Repeat {
            get {
                return ResourceManager.GetString("TextBlock_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   まとめて編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_Repeat_BulkEdit {
            get {
                return ResourceManager.GetString("TextBlock_Repeat_BulkEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   回数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_Repeat_Count {
            get {
                return ResourceManager.GetString("TextBlock_Repeat_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   休日設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_Repeat_Holiday {
            get {
                return ResourceManager.GetString("TextBlock_Repeat_Holiday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   置換 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_Replace {
            get {
                return ResourceManager.GetString("TextBlock_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存対象 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_SaveTarget {
            get {
                return ResourceManager.GetString("TextBlock_SaveTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_Search {
            get {
                return ResourceManager.GetString("TextBlock_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_Selection {
            get {
                return ResourceManager.GetString("TextBlock_Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   店名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_ShopName {
            get {
                return ResourceManager.GetString("TextBlock_ShopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SNS に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_SNS {
            get {
                return ResourceManager.GetString("TextBlock_SNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ソート順 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_SortOrder {
            get {
                return ResourceManager.GetString("TextBlock_SortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DBファイル名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_SQLite_DBFilePath {
            get {
                return ResourceManager.GetString("TextBlock_SQLite_DBFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開始日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_StartDate {
            get {
                return ResourceManager.GetString("TextBlock_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   開始月 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_StartMonth {
            get {
                return ResourceManager.GetString("TextBlock_StartMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   合計 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_Sum {
            get {
                return ResourceManager.GetString("TextBlock_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   サポート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_Support {
            get {
                return ResourceManager.GetString("TextBlock_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   タイミング に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_Timing {
            get {
                return ResourceManager.GetString("TextBlock_Timing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新履歴 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_UpdateHistory {
            get {
                return ResourceManager.GetString("TextBlock_UpdateHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全体 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TextBlock_Whole {
            get {
                return ResourceManager.GetString("TextBlock_Whole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リスト追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_AddListWindow {
            get {
                return ResourceManager.GetString("Title_AddListWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_AddMoveWindow {
            get {
                return ResourceManager.GetString("Title_AddMoveWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_AddWindow {
            get {
                return ResourceManager.GetString("Title_AddWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バックアップフォルダ選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_BackupFolderSelection {
            get {
                return ResourceManager.GetString("Title_BackupFolderSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   確認 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_Conformation {
            get {
                return ResourceManager.GetString("Title_Conformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSV比較 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_CsvComparisonWindow {
            get {
                return ResourceManager.GetString("Title_CsvComparisonWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSVフォルダ選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_CsvFolderSelection {
            get {
                return ResourceManager.GetString("Title_CsvFolderSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   初期設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_DbSettingWindow {
            get {
                return ResourceManager.GetString("Title_DbSettingWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リスト編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_EditListWindow {
            get {
                return ResourceManager.GetString("Title_EditListWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   移動編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_EditMoveWindow {
            get {
                return ResourceManager.GetString("Title_EditMoveWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_EditWindow {
            get {
                return ResourceManager.GetString("Title_EditWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_Error {
            get {
                return ResourceManager.GetString("Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_FileSelection {
            get {
                return ResourceManager.GetString("Title_FileSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_Information {
            get {
                return ResourceManager.GetString("Title_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Household Account Book に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_MainWindow {
            get {
                return ResourceManager.GetString("Title_MainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_SettingsWindow {
            get {
                return ResourceManager.GetString("Title_SettingsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   期間選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_TermSelectionWindow {
            get {
                return ResourceManager.GetString("Title_TermSelectionWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョン情報 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_VersionWindow {
            get {
                return ResourceManager.GetString("Title_VersionWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   警告 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title_Warning {
            get {
                return ResourceManager.GetString("Title_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSV一致チェック に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ToolTip_CheckIsMatch {
            get {
                return ResourceManager.GetString("ToolTip_CheckIsMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Unit_Day {
            get {
                return ResourceManager.GetString("Unit_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   年度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Unit_FiscalYear {
            get {
                return ResourceManager.GetString("Unit_FiscalYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   円 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Unit_Money {
            get {
                return ResourceManager.GetString("Unit_Money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   月 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Unit_Month {
            get {
                return ResourceManager.GetString("Unit_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   年 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Unit_Year {
            get {
                return ResourceManager.GetString("Unit_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   * 記録以前
        ///  記帳風月からのインポート
        ///  帳簿項目追加、編集
        ///  概要表示
        ///
        ///* 2016
        ///2016/12/29
        ///  MainWindow.xaml.cs
        ///    ＋削除時に移動も削除されるようにした(2017/01/01確認)
        ///    ↑移動操作可能の判定が「帳簿」ではなく「帳簿項目」になっていたのを修正した
        ///    ↑項目編集処理のグループ種別判定処理のSQLを修正した
        ///    ↑NumericUpDown.ValueのModeをTwoWayに修正した - Editしたテキストが取得できなかったため
        ///    ↑NumericUpDown内のTextBoxのUpdateSourceTriggerをPropertyChangedに修正した - Editしたテキストが取得できなかったため
        ///  ActionRegistrationWindow.xaml.cs
        ///    △グループに属する項目が1つになったときにグループを削除するように変更した
        ///    ↑登録完了時にDialogResult=trueとなるように修正した
        ///    ↑グループ内帳簿項目洗い出し時に日付昇順になるよう [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UpdateLog {
            get {
                return ResourceManager.GetString("UpdateLog", resourceCulture);
            }
        }
    }
}
