//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HouseholdAccountBook.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double MainWindow_Height {
            get {
                return ((double)(this["MainWindow_Height"]));
            }
            set {
                this["MainWindow_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double MainWindow_Width {
            get {
                return ((double)(this["MainWindow_Width"]));
            }
            set {
                this["MainWindow_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double ActionRegistrationWindow_Height {
            get {
                return ((double)(this["ActionRegistrationWindow_Height"]));
            }
            set {
                this["ActionRegistrationWindow_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double ActionRegistrationWindow_Width {
            get {
                return ((double)(this["ActionRegistrationWindow_Width"]));
            }
            set {
                this["ActionRegistrationWindow_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double MoveRegistrationWindow_Height {
            get {
                return ((double)(this["MoveRegistrationWindow_Height"]));
            }
            set {
                this["MoveRegistrationWindow_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double MoveRegistrationWindow_Width {
            get {
                return ((double)(this["MoveRegistrationWindow_Width"]));
            }
            set {
                this["MoveRegistrationWindow_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double MainWindow_Left {
            get {
                return ((double)(this["MainWindow_Left"]));
            }
            set {
                this["MainWindow_Left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double MainWindow_Top {
            get {
                return ((double)(this["MainWindow_Top"]));
            }
            set {
                this["MainWindow_Top"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double ActionRegistrationWindow_Left {
            get {
                return ((double)(this["ActionRegistrationWindow_Left"]));
            }
            set {
                this["ActionRegistrationWindow_Left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double ActionRegistrationWindow_Top {
            get {
                return ((double)(this["ActionRegistrationWindow_Top"]));
            }
            set {
                this["ActionRegistrationWindow_Top"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double MoveRegistrationWindow_Left {
            get {
                return ((double)(this["MoveRegistrationWindow_Left"]));
            }
            set {
                this["MoveRegistrationWindow_Left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double MoveRegistrationWindow_Top {
            get {
                return ((double)(this["MoveRegistrationWindow_Top"]));
            }
            set {
                this["MoveRegistrationWindow_Top"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int App_BackUpNum {
            get {
                return ((int)(this["App_BackUpNum"]));
            }
            set {
                this["App_BackUpNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("backup")]
        public string App_BackUpFolderPath {
            get {
                return ((string)(this["App_BackUpFolderPath"]));
            }
            set {
                this["App_BackUpFolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string App_Postgres_Host {
            get {
                return ((string)(this["App_Postgres_Host"]));
            }
            set {
                this["App_Postgres_Host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5432")]
        public int App_Postgres_Port {
            get {
                return ((int)(this["App_Postgres_Port"]));
            }
            set {
                this["App_Postgres_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string App_Postgres_UserName {
            get {
                return ((string)(this["App_Postgres_UserName"]));
            }
            set {
                this["App_Postgres_UserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string App_Postgres_Password {
            get {
                return ((string)(this["App_Postgres_Password"]));
            }
            set {
                this["App_Postgres_Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("account_book")]
        public string App_Postgres_DatabaseName {
            get {
                return ((string)(this["App_Postgres_DatabaseName"]));
            }
            set {
                this["App_Postgres_DatabaseName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int App_StartMonth {
            get {
                return ((int)(this["App_StartMonth"]));
            }
            set {
                this["App_StartMonth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int App_ColumnWidth_Value {
            get {
                return ((int)(this["App_ColumnWidth_Value"]));
            }
            set {
                this["App_ColumnWidth_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int MainWindow_SelectedBookId {
            get {
                return ((int)(this["MainWindow_SelectedBookId"]));
            }
            set {
                this["MainWindow_SelectedBookId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string App_KichoDBFilePath {
            get {
                return ((string)(this["App_KichoDBFilePath"]));
            }
            set {
                this["App_KichoDBFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string App_CustomFormatFilePath {
            get {
                return ((string)(this["App_CustomFormatFilePath"]));
            }
            set {
                this["App_CustomFormatFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string App_Postgres_DumpExePath {
            get {
                return ((string)(this["App_Postgres_DumpExePath"]));
            }
            set {
                this["App_Postgres_DumpExePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string App_Postgres_RestoreExePath {
            get {
                return ((string)(this["App_Postgres_RestoreExePath"]));
            }
            set {
                this["App_Postgres_RestoreExePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool App_InitFlag {
            get {
                return ((bool)(this["App_InitFlag"]));
            }
            set {
                this["App_InitFlag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string App_Postgres_Role {
            get {
                return ((string)(this["App_Postgres_Role"]));
            }
            set {
                this["App_Postgres_Role"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double ActionListRegistrationWindow_Width {
            get {
                return ((double)(this["ActionListRegistrationWindow_Width"]));
            }
            set {
                this["ActionListRegistrationWindow_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double ActionListRegistrationWindow_Top {
            get {
                return ((double)(this["ActionListRegistrationWindow_Top"]));
            }
            set {
                this["ActionListRegistrationWindow_Top"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double ActionListRegistrationWindow_Left {
            get {
                return ((double)(this["ActionListRegistrationWindow_Left"]));
            }
            set {
                this["ActionListRegistrationWindow_Left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double ActionListRegistrationWindow_Height {
            get {
                return ((double)(this["ActionListRegistrationWindow_Height"]));
            }
            set {
                this["ActionListRegistrationWindow_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("account_book_debug")]
        public string App_Postgres_DatabaseName_Debug {
            get {
                return ((string)(this["App_Postgres_DatabaseName_Debug"]));
            }
            set {
                this["App_Postgres_DatabaseName_Debug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string App_Version {
            get {
                return ((string)(this["App_Version"]));
            }
            set {
                this["App_Version"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int MainWindow_WindowState {
            get {
                return ((int)(this["MainWindow_WindowState"]));
            }
            set {
                this["MainWindow_WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double SettingsWindow_Height {
            get {
                return ((double)(this["SettingsWindow_Height"]));
            }
            set {
                this["SettingsWindow_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double SettingsWindow_Left {
            get {
                return ((double)(this["SettingsWindow_Left"]));
            }
            set {
                this["SettingsWindow_Left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double SettingsWindow_Top {
            get {
                return ((double)(this["SettingsWindow_Top"]));
            }
            set {
                this["SettingsWindow_Top"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double SettingsWindow_Width {
            get {
                return ((double)(this["SettingsWindow_Width"]));
            }
            set {
                this["SettingsWindow_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double CsvComparisonWindow_Height {
            get {
                return ((double)(this["CsvComparisonWindow_Height"]));
            }
            set {
                this["CsvComparisonWindow_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double CsvComparisonWindow_Left {
            get {
                return ((double)(this["CsvComparisonWindow_Left"]));
            }
            set {
                this["CsvComparisonWindow_Left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double CsvComparisonWindow_Top {
            get {
                return ((double)(this["CsvComparisonWindow_Top"]));
            }
            set {
                this["CsvComparisonWindow_Top"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double CsvComparisonWindow_Width {
            get {
                return ((double)(this["CsvComparisonWindow_Width"]));
            }
            set {
                this["CsvComparisonWindow_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string App_CsvFilePath {
            get {
                return ((string)(this["App_CsvFilePath"]));
            }
            set {
                this["App_CsvFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double TermWindow_Top {
            get {
                return ((double)(this["TermWindow_Top"]));
            }
            set {
                this["TermWindow_Top"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public double TermWindow_Left {
            get {
                return ((double)(this["TermWindow_Left"]));
            }
            set {
                this["TermWindow_Left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool App_BackUpFlagAtMinimizing {
            get {
                return ((bool)(this["App_BackUpFlagAtMinimizing"]));
            }
            set {
                this["App_BackUpFlagAtMinimizing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool App_BackUpFlagAtClosing {
            get {
                return ((bool)(this["App_BackUpFlagAtClosing"]));
            }
            set {
                this["App_BackUpFlagAtClosing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www8.cao.go.jp/chosei/shukujitsu/syukujitsu_kyujitsu.csv")]
        public string App_NationalHolidayCsv_Uri {
            get {
                return ((string)(this["App_NationalHolidayCsv_Uri"]));
            }
            set {
                this["App_NationalHolidayCsv_Uri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int App_NationalHolidayCsv_DateIndex {
            get {
                return ((int)(this["App_NationalHolidayCsv_DateIndex"]));
            }
            set {
                this["App_NationalHolidayCsv_DateIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int MainWindow_SelectedTabIndex {
            get {
                return ((int)(this["MainWindow_SelectedTabIndex"]));
            }
            set {
                this["MainWindow_SelectedTabIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int MainWindow_SelectedGraphKindIndex {
            get {
                return ((int)(this["MainWindow_SelectedGraphKindIndex"]));
            }
            set {
                this["MainWindow_SelectedGraphKindIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool App_IsDebug {
            get {
                return ((bool)(this["App_IsDebug"]));
            }
            set {
                this["App_IsDebug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool App_InitSizeFlag {
            get {
                return ((bool)(this["App_InitSizeFlag"]));
            }
            set {
                this["App_InitSizeFlag"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool App_IsPositionSaved {
            get {
                return ((bool)(this["App_IsPositionSaved"]));
            }
            set {
                this["App_IsPositionSaved"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int MainWindow_SelectedGraphKind2Index {
            get {
                return ((int)(this["MainWindow_SelectedGraphKind2Index"]));
            }
            set {
                this["MainWindow_SelectedGraphKind2Index"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1970-01-01")]
        public global::System.DateTime App_BackUpCurrentAtMinimizing {
            get {
                return ((global::System.DateTime)(this["App_BackUpCurrentAtMinimizing"]));
            }
            set {
                this["App_BackUpCurrentAtMinimizing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int App_BackUpIntervalMinAtMinimizing {
            get {
                return ((int)(this["App_BackUpIntervalMinAtMinimizing"]));
            }
            set {
                this["App_BackUpIntervalMinAtMinimizing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int App_Postgres_Password_Input {
            get {
                return ((int)(this["App_Postgres_Password_Input"]));
            }
            set {
                this["App_Postgres_Password_Input"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string App_SQLFilePath {
            get {
                return ((string)(this["App_SQLFilePath"]));
            }
            set {
                this["App_SQLFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ja-JP")]
        public string App_CultureName {
            get {
                return ((string)(this["App_CultureName"]));
            }
            set {
                this["App_CultureName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string App_OleDB_DBFilePath {
            get {
                return ((string)(this["App_OleDB_DBFilePath"]));
            }
            set {
                this["App_OleDB_DBFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string App_SQLite_DBFilePath {
            get {
                return ((string)(this["App_SQLite_DBFilePath"]));
            }
            set {
                this["App_SQLite_DBFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int App_SelectedDBKind {
            get {
                return ((int)(this["App_SelectedDBKind"]));
            }
            set {
                this["App_SelectedDBKind"] = value;
            }
        }
    }
}
